name: 'CI'
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    name: 'Validate'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run validate
